"""Shared enumerations. Stored as strings so schema changes are plain migrations."""

from enum import StrEnum


class Role(StrEnum):
    ADMIN = "admin"
    ANALYST = "analyst"
    VIEWER = "viewer"


class CaseStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class Priority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TargetType(StrEnum):
    DOMAIN = "DOMAIN"
    IP = "IP"
    EMAIL = "EMAIL"
    USERNAME = "USERNAME"
    ORGANIZATION = "ORGANIZATION"
    PERSON = "PERSON"
    SOCIAL_ACCOUNT = "SOCIAL_ACCOUNT"
    URL = "URL"
    COMPANY = "COMPANY"
    DOCUMENT = "DOCUMENT"
    CRYPTO_ADDRESS = "CRYPTO_ADDRESS"
    PHONE = "PHONE"
    UNKNOWN = "UNKNOWN"


class InvestigationStatus(StrEnum):
    DRAFT = "DRAFT"
    PLANNING = "PLANNING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    DISABLED = "DISABLED"


class EventType(StrEnum):
    PLAN = "PLAN"
    PLAN_APPROVED = "PLAN_APPROVED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_SKIPPED = "TASK_SKIPPED"
    SEARCH_STARTED = "SEARCH_STARTED"
    QUERY_EXECUTED = "QUERY_EXECUTED"
    RESULTS_FOUND = "RESULTS_FOUND"
    SOURCE_FETCHED = "SOURCE_FETCHED"
    SOURCE_DISCOVERED = "SOURCE_DISCOVERED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    ENTITY_DISCOVERED = "ENTITY_DISCOVERED"
    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    FINDING_CREATED = "FINDING_CREATED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    AI_MESSAGE = "AI_MESSAGE"
    AI_TOOL_CALL = "AI_TOOL_CALL"
    AI_CLAIM_REJECTED = "AI_CLAIM_REJECTED"
    WARNING = "WARNING"
    ERROR = "ERROR"
    STATUS_CHANGED = "STATUS_CHANGED"
    REPORT_READY = "REPORT_READY"
    INFO = "INFO"


class SourceType(StrEnum):
    WEBSITE = "WEBSITE"
    SEARCH_RESULT = "SEARCH_RESULT"
    NEWS = "NEWS"
    SOCIAL = "SOCIAL"
    FORUM = "FORUM"
    CODE_REPOSITORY = "CODE_REPOSITORY"
    TECHNICAL_RECORD = "TECHNICAL_RECORD"
    ARCHIVE = "ARCHIVE"
    DOCUMENT = "DOCUMENT"
    API = "API"
    OTHER = "OTHER"


class EvidenceType(StrEnum):
    DIRECT_STATEMENT = "DIRECT_STATEMENT"
    TECHNICAL_RECORD = "TECHNICAL_RECORD"
    DOCUMENT = "DOCUMENT"
    PUBLIC_STATEMENT = "PUBLIC_STATEMENT"
    ALLEGATION = "ALLEGATION"
    SYSTEM_INTERPRETATION = "SYSTEM_INTERPRETATION"
    ARCHIVE_SNAPSHOT = "ARCHIVE_SNAPSHOT"
    SCREENSHOT = "SCREENSHOT"


class Confidence(StrEnum):
    CONFIRMED = "CONFIRMED"
    CORROBORATED = "CORROBORATED"
    SUPPORTED = "SUPPORTED"
    POSSIBLE = "POSSIBLE"
    INFERENCE = "INFERENCE"
    UNVERIFIED = "UNVERIFIED"
    CONTRADICTED = "CONTRADICTED"


class ReviewState(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    NEEDS_VERIFICATION = "NEEDS_VERIFICATION"


class EntityType(StrEnum):
    PERSON = "PERSON"
    USERNAME = "USERNAME"
    EMAIL = "EMAIL"
    DOMAIN = "DOMAIN"
    IP = "IP"
    URL = "URL"
    ORGANIZATION = "ORGANIZATION"
    COMPANY = "COMPANY"
    LOCATION = "LOCATION"
    PHONE = "PHONE"
    SOCIAL_ACCOUNT = "SOCIAL_ACCOUNT"
    REPOSITORY = "REPOSITORY"
    DOCUMENT = "DOCUMENT"
    ARTICLE = "ARTICLE"
    EVENT = "EVENT"
    CRYPTO_ADDRESS = "CRYPTO_ADDRESS"
    ASN = "ASN"
    CERTIFICATE = "CERTIFICATE"
    NAMESERVER = "NAMESERVER"
    MAIL_SERVER = "MAIL_SERVER"
    TECHNOLOGY = "TECHNOLOGY"


class RelationshipType(StrEnum):
    MENTIONS = "MENTIONS"
    LINKS_TO = "LINKS_TO"
    OWNS = "OWNS"
    AUTHORED = "AUTHORED"
    REFERENCES = "REFERENCES"
    HOSTED_ON = "HOSTED_ON"
    RESOLVES_TO = "RESOLVES_TO"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    POSSIBLY_SAME_ENTITY = "POSSIBLY_SAME_ENTITY"
    CONFIRMED_BY_SOURCE = "CONFIRMED_BY_SOURCE"
    USES_NAMESERVER = "USES_NAMESERVER"
    USES_MAIL_SERVER = "USES_MAIL_SERVER"
    SUBDOMAIN_OF = "SUBDOMAIN_OF"
    REGISTERED_BY = "REGISTERED_BY"
    ISSUED_FOR = "ISSUED_FOR"
    MEMBER_OF = "MEMBER_OF"


class ReportFormat(StrEnum):
    MARKDOWN = "markdown"
    HTML = "html"
    PDF = "pdf"
    DOCX = "docx"


class AlertType(StrEnum):
    NEW_SOURCE = "NEW_SOURCE"
    NEW_ENTITY = "NEW_ENTITY"
    NEW_RELATIONSHIP = "NEW_RELATIONSHIP"
    SOURCE_CHANGE = "SOURCE_CHANGE"
    DOMAIN_CHANGE = "DOMAIN_CHANGE"
    CERTIFICATE_CHANGE = "CERTIFICATE_CHANGE"
    KEYWORD_MATCH = "KEYWORD_MATCH"
    CONFLICTING_INFORMATION = "CONFLICTING_INFORMATION"
    MONITOR_ERROR = "MONITOR_ERROR"


class AuditAction(StrEnum):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    USER_CREATED = "USER_CREATED"
    LOGIN_FAILED = "LOGIN_FAILED"
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    CASE_DELETED = "CASE_DELETED"
    CASE_CLONED = "CASE_CLONED"
    TARGET_CREATED = "TARGET_CREATED"
    INVESTIGATION_CREATED = "INVESTIGATION_CREATED"
    INVESTIGATION_STARTED = "INVESTIGATION_STARTED"
    INVESTIGATION_APPROVED = "INVESTIGATION_APPROVED"
    INVESTIGATION_PAUSED = "INVESTIGATION_PAUSED"
    INVESTIGATION_RESUMED = "INVESTIGATION_RESUMED"
    INVESTIGATION_STOPPED = "INVESTIGATION_STOPPED"
    SEARCH_STARTED = "SEARCH_STARTED"
    QUERY_EXECUTED = "QUERY_EXECUTED"
    SOURCE_DISCOVERED = "SOURCE_DISCOVERED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    EVIDENCE_REVIEWED = "EVIDENCE_REVIEWED"
    ENTITY_CREATED = "ENTITY_CREATED"
    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    RELATIONSHIP_REVIEWED = "RELATIONSHIP_REVIEWED"
    FINDING_CREATED = "FINDING_CREATED"
    FINDING_REVIEWED = "FINDING_REVIEWED"
    NOTE_CREATED = "NOTE_CREATED"
    REPORT_GENERATED = "REPORT_GENERATED"
    MONITOR_CREATED = "MONITOR_CREATED"
    MONITOR_RUN = "MONITOR_RUN"
    ALERT_CREATED = "ALERT_CREATED"
    CONFIG_CHANGED = "CONFIG_CHANGED"
    EXPORT_CREATED = "EXPORT_CREATED"
    IMPORT_COMPLETED = "IMPORT_COMPLETED"
    AI_QUERY = "AI_QUERY"
