"""initial schema

Revision ID: 83d25e2b9aaa
Revises:
Create Date: 2026-10-02 07:28:33.849955+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "83d25e2b9aaa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "id_sequences",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_id_sequences")),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "preferences", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "api_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_api_tokens_token_digest")),
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_tokens_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_label", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("object_type", sa.String(length=64), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index("ix_audit_logs_action_created", ["action", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)

    op.create_table(
        "cases",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("analyst_id", sa.Uuid(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("cloned_from_id", sa.Uuid(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analyst_id"], ["users.id"], name=op.f("fk_cases_analyst_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["cloned_from_id"], ["cases.id"], name=op.f("fk_cases_cloned_from_id_cases"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cases_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_cases_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_cases_status"), ["status"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_sessions_token_digest")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "entities",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column(
            "evidence_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("is_target", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_entities_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["merged_into_id"], ["entities.id"], name=op.f("fk_entities_merged_into_id_entities"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entities_case_id"), ["case_id"], unique=False)
        batch_op.create_index("ix_entities_case_type_value", ["case_id", "type", "normalized_value"], unique=True)
        batch_op.create_index(batch_op.f("ix_entities_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_entities_normalized_value"), ["normalized_value"], unique=False)
        batch_op.create_index(batch_op.f("ix_entities_type"), ["type"], unique=False)

    op.create_table(
        "investigations",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("request_text", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("plan", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("plan_rationale", sa.Text(), nullable=False),
        sa.Column("plan_source", sa.String(length=32), nullable=False),
        sa.Column("bounds", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("stats", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("control_flag", sa.String(length=16), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_investigations_approved_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_investigations_case_id_cases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
    )
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investigations_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_investigations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_investigations_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_investigations_status"), ["status"], unique=False)

    op.create_table(
        "notes",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column(
            "entity_refs", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "evidence_refs", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "attachments", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_notes_author_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_notes_case_id_cases"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notes_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notes_created_at"), ["created_at"], unique=False)

    op.create_table(
        "reports",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generation_ms", sa.Integer(), nullable=True),
        sa.Column(
            "options", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("stats", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_reports_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_reports_generated_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_display_id"), ["display_id"], unique=True)

    op.create_table(
        "sources",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=256), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("publisher", sa.String(length=256), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("reliability_note", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_sources_case_id_cases"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_canonical_url"), ["canonical_url"], unique=False)
        batch_op.create_index("ix_sources_case_canonical", ["case_id", "canonical_url"], unique=True)
        batch_op.create_index(batch_op.f("ix_sources_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_collector"), ["collector"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_sources_domain"), ["domain"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_source_type"), ["source_type"], unique=False)

    op.create_table(
        "findings",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("assessment", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column(
            "confidence_rationale",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("proposed_by", sa.String(length=32), nullable=False),
        sa.Column("review_state", sa.String(length=24), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column(
            "entity_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "relationship_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_findings_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_findings_investigation_id_investigations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_findings_reviewed_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_confidence"), ["confidence"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_findings_investigation_id"), ["investigation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_review_state"), ["review_state"], unique=False)

    op.create_table(
        "investigation_tasks",
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("params", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column(
            "result_summary", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_investigation_tasks_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation_tasks")),
    )
    with op.batch_alter_table("investigation_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investigation_tasks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_investigation_tasks_investigation_id"), ["investigation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_investigation_tasks_status"), ["status"], unique=False)

    op.create_table(
        "relationships",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("source_entity_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("review_state", sa.String(length=24), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_relationships_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_relationships_reviewed_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["entities.id"],
            name=op.f("fk_relationships_source_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["entities.id"],
            name=op.f("fk_relationships_target_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_relationships_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_relationships_source_entity_id"), ["source_entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_target_entity_id"), ["target_entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_relationships_type"), ["type"], unique=False)
        batch_op.create_index(
            "ix_relationships_unique", ["case_id", "source_entity_id", "target_entity_id", "type"], unique=True
        )

    op.create_table(
        "report_sections",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column(
            "cited_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"], ["reports.id"], name=op.f("fk_report_sections_report_id_reports"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_sections")),
    )
    with op.batch_alter_table("report_sections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_sections_report_id"), ["report_id"], unique=False)

    op.create_table(
        "source_snapshots",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("text_chars", sa.Integer(), nullable=False),
        sa.Column("artifact_path", sa.Text(), nullable=True),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("fetch_ms", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_source_snapshots_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_source_snapshots_source_id_sources"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
    )
    with op.batch_alter_table("source_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_snapshots_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_snapshots_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_snapshots_retrieved_at"), ["retrieved_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_snapshots_source_id"), ["source_id"], unique=False)

    op.create_table(
        "targets",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=1024), nullable=False),
        sa.Column("normalized_value", sa.String(length=1024), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("extra", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_targets_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_targets_entity_id_entities"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_targets")),
    )
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_targets_case_id"), ["case_id"], unique=False)
        batch_op.create_index("ix_targets_case_type_value", ["case_id", "type", "normalized_value"], unique=True)
        batch_op.create_index(batch_op.f("ix_targets_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_targets_normalized_value"), ["normalized_value"], unique=False)
        batch_op.create_index(batch_op.f("ix_targets_type"), ["type"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("excerpt_verified", sa.Boolean(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("collector", sa.String(length=64), nullable=False),
        sa.Column("collection_method", sa.String(length=64), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("review_state", sa.String(length=24), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "structured", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "entity_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("redacted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_evidence_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_evidence_investigation_id_investigations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_evidence_reviewed_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_evidence_snapshot_id_source_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_evidence_source_id_sources"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_confidence"), ["confidence"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_evidence_evidence_type"), ["evidence_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_investigation_id"), ["investigation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_review_state"), ["review_state"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_source_id"), ["source_id"], unique=False)

    op.create_table(
        "investigation_events",
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("data", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_investigation_events_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_investigation_events_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["investigation_tasks.id"],
            name=op.f("fk_investigation_events_task_id_investigation_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation_events")),
    )
    with op.batch_alter_table("investigation_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investigation_events_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_investigation_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_investigation_events_inv_seq", ["investigation_id", "seq"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_investigation_events_investigation_id"), ["investigation_id"], unique=False
        )

    op.create_table(
        "monitors",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("target_value", sa.String(length=1024), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("checks", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("schedule", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "keywords", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "baseline", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("notify", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_monitors_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_id"], ["targets.id"], name=op.f("fk_monitors_target_id_targets"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitors")),
    )
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monitors_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_monitors_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_monitors_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_monitors_next_run_at"), ["next_run_at"], unique=False)

    op.create_table(
        "search_queries",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("branch", sa.String(length=128), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_search_queries_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_search_queries_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["investigation_tasks.id"],
            name=op.f("fk_search_queries_task_id_investigation_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_queries")),
    )
    with op.batch_alter_table("search_queries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_queries_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_queries_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_queries_investigation_id"), ["investigation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_queries_query_hash"), ["query_hash"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("display_id", sa.String(length=24), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("source_label", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("data", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "delivered", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"], ["users.id"], name=op.f("fk_alerts_acknowledged_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_alerts_case_id_cases"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_alerts_evidence_id_evidence"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitors.id"], name=op.f("fk_alerts_monitor_id_monitors"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_alert_type"), ["alert_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_display_id"), ["display_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_alerts_monitor_id"), ["monitor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_read"), ["read"], unique=False)

    op.create_table(
        "entity_aliases",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("alias_type", sa.String(length=32), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name=op.f("fk_entity_aliases_entity_id_entities"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_entity_aliases_evidence_id_evidence"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_aliases")),
    )
    with op.batch_alter_table("entity_aliases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entity_aliases_alias"), ["alias"], unique=False)
        batch_op.create_index(batch_op.f("ix_entity_aliases_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "evidence_artifacts",
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_evidence_artifacts_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_evidence_artifacts_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_evidence_artifacts_source_id_sources"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_artifacts")),
    )
    with op.batch_alter_table("evidence_artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_artifacts_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_artifacts_evidence_id"), ["evidence_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evidence_artifacts_sha256"), ["sha256"], unique=False)

    op.create_table(
        "finding_evidence",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_finding_evidence_evidence_id_evidence"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"], ["findings.id"], name=op.f("fk_finding_evidence_finding_id_findings"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("finding_id", "evidence_id", name=op.f("pk_finding_evidence")),
    )
    op.create_table(
        "relationship_evidence",
        sa.Column("relationship_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_relationship_evidence_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relationship_id"],
            ["relationships.id"],
            name=op.f("fk_relationship_evidence_relationship_id_relationships"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("relationship_id", "evidence_id", name=op.f("pk_relationship_evidence")),
    )
    op.create_table(
        "search_results",
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=256), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("engine", sa.String(length=64), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_search_results_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["search_queries.id"],
            name=op.f("fk_search_results_query_id_search_queries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_search_results_source_id_sources"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_results")),
    )
    with op.batch_alter_table("search_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_results_canonical_url"), ["canonical_url"], unique=False)
        batch_op.create_index("ix_search_results_case_canonical", ["case_id", "canonical_url"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_results_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_results_domain"), ["domain"], unique=False)
        batch_op.create_index(batch_op.f("ix_search_results_query_id"), ["query_id"], unique=False)

    op.create_table(
        "timeline_events",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("precision", sa.String(length=8), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_kind", sa.String(length=32), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column(
            "entity_ids", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_timeline_events_case_id_cases"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_timeline_events_evidence_id_evidence"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
    )
    with op.batch_alter_table("timeline_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_timeline_events_case_id"), ["case_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_timeline_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_timeline_events_occurred_at"), ["occurred_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("timeline_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timeline_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_timeline_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_timeline_events_case_id"))

    op.drop_table("timeline_events")
    with op.batch_alter_table("search_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_results_query_id"))
        batch_op.drop_index(batch_op.f("ix_search_results_domain"))
        batch_op.drop_index(batch_op.f("ix_search_results_case_id"))
        batch_op.drop_index("ix_search_results_case_canonical")
        batch_op.drop_index(batch_op.f("ix_search_results_canonical_url"))

    op.drop_table("search_results")
    op.drop_table("relationship_evidence")
    op.drop_table("finding_evidence")
    with op.batch_alter_table("evidence_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_artifacts_sha256"))
        batch_op.drop_index(batch_op.f("ix_evidence_artifacts_evidence_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_artifacts_case_id"))

    op.drop_table("evidence_artifacts")
    with op.batch_alter_table("entity_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_aliases_entity_id"))
        batch_op.drop_index(batch_op.f("ix_entity_aliases_alias"))

    op.drop_table("entity_aliases")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_read"))
        batch_op.drop_index(batch_op.f("ix_alerts_monitor_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_display_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_created_at"))
        batch_op.drop_index(batch_op.f("ix_alerts_case_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_alert_type"))

    op.drop_table("alerts")
    with op.batch_alter_table("search_queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_queries_query_hash"))
        batch_op.drop_index(batch_op.f("ix_search_queries_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_search_queries_created_at"))
        batch_op.drop_index(batch_op.f("ix_search_queries_case_id"))

    op.drop_table("search_queries")
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitors_next_run_at"))
        batch_op.drop_index(batch_op.f("ix_monitors_display_id"))
        batch_op.drop_index(batch_op.f("ix_monitors_created_at"))
        batch_op.drop_index(batch_op.f("ix_monitors_case_id"))

    op.drop_table("monitors")
    with op.batch_alter_table("investigation_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigation_events_investigation_id"))
        batch_op.drop_index("ix_investigation_events_inv_seq")
        batch_op.drop_index(batch_op.f("ix_investigation_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_investigation_events_case_id"))

    op.drop_table("investigation_events")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_source_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_review_state"))
        batch_op.drop_index(batch_op.f("ix_evidence_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_evidence_type"))
        batch_op.drop_index(batch_op.f("ix_evidence_display_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_created_at"))
        batch_op.drop_index(batch_op.f("ix_evidence_content_hash"))
        batch_op.drop_index(batch_op.f("ix_evidence_confidence"))
        batch_op.drop_index(batch_op.f("ix_evidence_case_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_type"))
        batch_op.drop_index(batch_op.f("ix_targets_normalized_value"))
        batch_op.drop_index(batch_op.f("ix_targets_created_at"))
        batch_op.drop_index("ix_targets_case_type_value")
        batch_op.drop_index(batch_op.f("ix_targets_case_id"))

    op.drop_table("targets")
    with op.batch_alter_table("source_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_snapshots_source_id"))
        batch_op.drop_index(batch_op.f("ix_source_snapshots_retrieved_at"))
        batch_op.drop_index(batch_op.f("ix_source_snapshots_content_hash"))
        batch_op.drop_index(batch_op.f("ix_source_snapshots_case_id"))

    op.drop_table("source_snapshots")
    with op.batch_alter_table("report_sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_sections_report_id"))

    op.drop_table("report_sections")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index("ix_relationships_unique")
        batch_op.drop_index(batch_op.f("ix_relationships_type"))
        batch_op.drop_index(batch_op.f("ix_relationships_target_entity_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_source_entity_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_display_id"))
        batch_op.drop_index(batch_op.f("ix_relationships_created_at"))
        batch_op.drop_index(batch_op.f("ix_relationships_case_id"))

    op.drop_table("relationships")
    with op.batch_alter_table("investigation_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigation_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_investigation_tasks_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_investigation_tasks_created_at"))

    op.drop_table("investigation_tasks")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_review_state"))
        batch_op.drop_index(batch_op.f("ix_findings_investigation_id"))
        batch_op.drop_index(batch_op.f("ix_findings_display_id"))
        batch_op.drop_index(batch_op.f("ix_findings_created_at"))
        batch_op.drop_index(batch_op.f("ix_findings_confidence"))
        batch_op.drop_index(batch_op.f("ix_findings_category"))
        batch_op.drop_index(batch_op.f("ix_findings_case_id"))

    op.drop_table("findings")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_source_type"))
        batch_op.drop_index(batch_op.f("ix_sources_domain"))
        batch_op.drop_index(batch_op.f("ix_sources_display_id"))
        batch_op.drop_index(batch_op.f("ix_sources_created_at"))
        batch_op.drop_index(batch_op.f("ix_sources_collector"))
        batch_op.drop_index(batch_op.f("ix_sources_case_id"))
        batch_op.drop_index("ix_sources_case_canonical")
        batch_op.drop_index(batch_op.f("ix_sources_canonical_url"))

    op.drop_table("sources")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_display_id"))
        batch_op.drop_index(batch_op.f("ix_reports_created_at"))
        batch_op.drop_index(batch_op.f("ix_reports_case_id"))

    op.drop_table("reports")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_created_at"))
        batch_op.drop_index(batch_op.f("ix_notes_case_id"))

    op.drop_table("notes")
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigations_status"))
        batch_op.drop_index(batch_op.f("ix_investigations_display_id"))
        batch_op.drop_index(batch_op.f("ix_investigations_created_at"))
        batch_op.drop_index(batch_op.f("ix_investigations_case_id"))

    op.drop_table("investigations")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_type"))
        batch_op.drop_index(batch_op.f("ix_entities_normalized_value"))
        batch_op.drop_index(batch_op.f("ix_entities_display_id"))
        batch_op.drop_index(batch_op.f("ix_entities_created_at"))
        batch_op.drop_index("ix_entities_case_type_value")
        batch_op.drop_index(batch_op.f("ix_entities_case_id"))

    op.drop_table("entities")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_status"))
        batch_op.drop_index(batch_op.f("ix_cases_display_id"))
        batch_op.drop_index(batch_op.f("ix_cases_created_at"))

    op.drop_table("cases")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_case_id"))
        batch_op.drop_index("ix_audit_logs_action_created")
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_tokens_created_at"))

    op.drop_table("api_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_table("id_sequences")
    # ### end Alembic commands ###
